### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
Can you add a travis build?

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

Can you add a travis and npm badge to the readme? Maybe use "shields.io"?
See for example: https://raw.githubusercontent.com/cargomedia/bipbip/master/README.md

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
lgtm!

**Pull request merged**
