### PR TITLE
Add support for "deploy:restart"

### PR DESCRIPTION
**Pull request by vogdb**
Depends on #26

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
- This is to restart the application, so I would suggest:
 - Adjust wordings. E.g. "Restarting the application…". Success msg could be just "Done."?
 - index.js: Same. Just "Restart application"?

**Comment by vogdb** [comment]
If it to restart an application then what are the arguments?
```
hubot deploy restart <application> <environment>
```
or
```
hubot deploy restart <application>
```
?

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
All pulsar jobs need application and environment, should be the same for restart.

lgtm

**Pull request merged**
