### PR TITLE
Travis NPM deploy didn't work

### PR DESCRIPTION
**Pull request by vogdb**
https://travis-ci.org/cargomedia/hubot-pulsar/builds/123070708

```
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
npm ERR! publish Failed PUT 401
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.13/bin/node" "/home/travis/.nvm/versions/node/v0.12.13/bin/npm" "publish"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code E401
npm ERR! You must be logged in to publish packages : hubot-pulsar
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/cargomedia/hubot-pulsar/npm-debug.log
```

### CODE REVIEW

**Comment by vogdb** [comment]
I hope this will help. @njam please look

**Comment by njam** [comment]
ok, can you also bump the version so we can test it?

**Comment by vogdb** [comment]
worked!

**Comment by njam** [comment]
👍

**Pull request merged**
