### PR TITLE
Rewrite it in javascript.

### PR DESCRIPTION
**Pull request by vogdb**
I can't bear with coffescript anymore. Silent errors, tabs. Waste of time...

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
- Update readme.md
- package.json: Remove coffee-script?
- src/index.js: Did you confirm this docu is still parsed correctly?

**Comment by vogdb** [comment]
> - src/index.js: Did you confirm this docu is still parsed correctly?

Yes. Correctly

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
