### PR TITLE
Fix job idle monitor process

### PR DESCRIPTION
**Pull request by vogdb**
- By default should not print any job output
- If it didn't change for some time it should print: "Running Xsecs: last line" (`idle`)
- When it changes after that it should print: "Continuing…" (`idle:resume`?)

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
Acceptance testing:
- The "Running…" message continues to be sent even when the job has stopped.
- The "Running…" message did not include any output
- The "continuing…" message is displayed on *every* message

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
