### PR TITLE
Add support for "deploy:rollback"

### PR DESCRIPTION
**Pull request by vogdb**
Depends on #28

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by vogdb** [comment]
Now I'm thinking. Should we ask for the confirmation from the user to rollback? I think it would be useful. @njam ?

**Comment by njam** [comment]
Hm I think a confirmation is not necessarily needed,  because there is no new information posted by the bot. So I should know already if I want to roll back or not during the release.

But about the "monitor" - should this maybe cover all jobs, not only deploy jobs? So that while a rollback is in progress we cannot start a deployment?

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
- index.js: description - how about: "Roll back to the previous release"?
- deploy.js: Check for "deployer" role
- deploy.js: I think we should make sure the "deploymentMonitor" acts as a mutex for *all* jobs, even for rollbacks. Because we should avoid that a deployment and a rollback run at the same time?

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
- deploy.js: pending: Don't use mutex - "pending" can run in parallel with other jobs I think!
- DeployMutex: Add getter `getJobWithTask(task)` to simplify deploy.js?
- DeployMutex: Add docus
- Did you test it?

**Comment by vogdb** [comment]
> - Did you test it?

so so. I planned to add tests in another PR.

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
- deploy.js: Remove console.log
- deploy.js: formatting

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
